### ISSUE TITLE
Exclusion of the Loading time from user-input time

### ISSUE THREAD

**Issue by roushandas02** [Daksh777/TakeABreak#10]
Hello @Daksh777 ,

The starting loading time of 5 seconds is added to the time the user asks. So it should be excluded from that time and the user should get his full time.

Thanks and Regards,
Roushan Das,
A GSSOC Contributor.

**Comment by Daksh777** [comment]
Good suggestion, you may start contributing from 1st March.

**Comment by roushandas02** [comment]
Thank you for assigning me this task. I will start my contribution from 1st March.
