### ISSUE TITLE
UI Enhancement of Main Page & adding hover effect.

### ISSUE THREAD

**Issue by kalashvasaniya** [Daksh777/TakeABreak#100]
### Is your feature request related to a problem? Please describe.

UI Enhancement of Main Page & adding hover effect.

### Describe the solution you'd like.

I Make This Project With the help of HTML, CSS & JavaScript.

### Describe alternatives you've considered.

The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!

**Comment by Daksh777** [comment]
Please explain more on what you're going to do

**Comment by kalashvasaniya** [comment]
> Please explain more on what you're going to do

Hover effect 
shadow effet
Font ig
UI another level
& more if needed

**Comment by Daksh777** [comment]
Please go into more detail.
Where will you add the hover effects? Where will you add the shadow effects? What do you mean by "UI another level"?
I intend to keep the UI and fonts as minimalistic as they are right now

**Comment by Daksh777** [comment]
I don't think none of it is required, I'll close this issue.
