### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Divyansh1315** [Daksh777/TakeABreak#102]
Whenever a user visits a website it looks for a  logo.

Take A Break works as a technique to tackle procrastination. 

A logo above Take A Break would look nice  according to me.

![image](https://user-images.githubusercontent.com/85311608/158008995-9c7fda89-a46d-4e70-83b3-77a8e927aac7.png)

I've created the logo in multiple backgrounds in order to make it look nice with different backgrounds.

**Comment by Daksh777** [comment]
We already have a logo which can be seen in the readme, I can send you that and you can add it to the website above the title

**Comment by Saurabh-Suchak** [comment]
hey, I would like to work on this.

**Comment by Divyansh1315** [comment]
> We already have a logo which can be seen in the readme, I can send you that and you can add it to the website above the title

Okkay you can send me that file on Discord DV#3650

**Comment by Divyansh1315** [comment]
> hey, I would like to work on this.

Hi Saurabh, I'm already working on this issue. You can take any other issue and create one of yours. 
Keep contributing!!

**Comment by Saurabh-Suchak** [comment]
> > hey, I would like to work on this.
> 
> Hi Saurabh, I'm already working on this issue. You can take any other issue and create one of yours. Keep contributing!!

yeah but since no one was assigned this issue, I thought to contribute on this one .

**Comment by Divyansh1315** [comment]
> We already have a logo which can be seen in the readme, I can send you that and you can add it to the website above the title

I'm facing an issue while adding the logo. Logo is not visible whereas if I use any other image instead of logo that is visible.


![2022-03-16 01_41_25-Take a Break - Self-Destructing Tabs](https://user-images.githubusercontent.com/85311608/158463190-820076cb-7007-490d-a9a7-3e9752d46b3e.png)


![2022-03-16 01_38_15-Take a Break - Self-Destructing Tabs](https://user-images.githubusercontent.com/85311608/158463215-62a58bb0-7766-4023-a562-7199f5c93e66.png)

**Comment by Sakshi-1701** [comment]
Hello @Daksh777 
I would love to work on this.
It would be great if you could assign this issue to me.

**Comment by Daksh777** [comment]
It's already assigned to @Divyansh1315, @Sakshi-1701

**Comment by Daksh777** [comment]
Any updates @Divyansh1315?

**Comment by Divyansh1315** [comment]
Sorry, @Daksh777  I was busy with academics these days...I'll make a Pull request by morning.

**Comment by Daksh777** [comment]
Sure @Divyansh1315

**Comment by ishabhthakur** [comment]
hey @Daksh777  i want to contribute to your project please assign me this issue!! under GSSOC'22 !!!  
I have new solution regarding this issues

**Comment by Daksh777** [comment]
If @Divyansh1315 is unable to do it, I'll assign it to you

**Comment by Divyansh1315** [comment]
Hi...I've added the logo should I move ahead to make the PR?

![2022-04-02 20_54_30-](https://user-images.githubusercontent.com/85311608/161390028-8d9ed947-5338-4f5e-8fd5-814bf3496362.png)
![2022-04-02 20_55_02-Take a Break - Self-Destructing Tabs](https://user-images.githubusercontent.com/85311608/161390035-d5159e48-d7e8-4c41-8ac3-01e1af267452.png)

**Comment by Daksh777** [comment]
Yes @Divyansh1315

**Comment by Anushruth-Reddy** [comment]
@Divyansh1315 is this issue still open?  If yes I would like to help/ work on it !

**Comment by Daksh777** [comment]
Since there are multiple who've asked to be assigned to the issue, if @Divyansh1315 gives no response within a day or two, I'll assign this to @Saurabh-Suchak who asked to be assigned to it after @Divyansh1315

**Comment by Anushruth-Reddy** [comment]
@Daksh777 is this issue still open? If yes I would like to help/ work on it !

**Comment by Susmita-Dey** [comment]
@Daksh777 Is the issue still open? If yes, I would like to work on this issue.

**Comment by PraveenaPulagam** [comment]
can you please assign me this issue if this issue is still open..

**Comment by Daksh777** [comment]
Since @Sakshi-1701 asked first, would you like to work on this @Sakshi-1701?

**Comment by Sakshi-1701** [comment]
@Daksh777 Yeah!

**Comment by Daksh777** [comment]
Please use the following SVG @Sakshi-1701 
![Group_2](https://user-images.githubusercontent.com/43648146/163809237-68c5b4c5-d1ca-4e03-9a4a-2f714c4f7ae1.svg)

**Comment by Susmita-Dey** [comment]
Kindly assign this issue to me. 
I'm a GSSoC'22 contributor. I can handle this issue.

**Comment by Susmita-Dey** [comment]
@Daksh777 Will the logo be centered in the middle or in the top left corner?

**Comment by Daksh777** [comment]
In the middle, like the picture here: 
![image](https://user-images.githubusercontent.com/43648146/167248961-faeebe05-e233-43c6-b17c-1bcb56bcb283.png)

**Comment by Susmita-Dey** [comment]
> In the middle, like the picture here: ![image](https://user-images.githubusercontent.com/43648146/167248961-faeebe05-e233-43c6-b17c-1bcb56bcb283.png)

Okay
