### ISSUE TITLE
Having a time up emoji

### ISSUE THREAD

**Issue by Saurabh-Suchak** [Daksh777/TakeABreak#104]
Having a time up emoji in place of a tick after the timer countdown finishes would make it look even better. If this change is approved, I would like to work on it.

**Comment by Daksh777** [comment]
Can you please explain more? I didn't get what you mean.

**Comment by Saurabh-Suchak** [comment]
> Can you please explain more? I didn't get what you mean.

After the countdown ends, there is a pop up with a motivational quote. Above it there is a tick ✅ logo, I am asking to replace that logo with a time up emoji.

**Comment by Daksh777** [comment]
Sounds good, but I don't think that's possible since that icon is from sweetalert2 and it can't be modified.

**Comment by Saurabh-Suchak** [comment]
then I guess the whole pop up window needs to be changed for it.

**Comment by Daksh777** [comment]
I don't think we should do that then, I'll have to close this, unfortunately.
