### ISSUE TITLE
Apply some small tilting effects on cards

### ISSUE THREAD

**Issue by Kumar-laxmi** [Daksh777/TakeABreak#105]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/76027425/158108279-e32cfdc3-f0af-4244-8dcf-b01b07f5b8d5.png)

The cards specifying timer could be made more cool if we apply some JS functions to improve tilting effect with minor tilting.

It would look really nice!

### Describe the solution you'd like.

To do this I will use Vanilla-Tilt-JS Library.

### Describe alternatives you've considered.

If I have to implement this without the library then I can design the JS functions my self.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/76027425/158108622-b156d07d-6ea8-4d08-b951-26ea37dd4fb1.png)

It would create a parallax effect to the text when mouse are hovered.

**Comment by Daksh777** [comment]
Thank you for your suggestion @Kumar-laxmi 
I believe that this will harm the minimalism and simplicity of the website so I'll have to close this.
