### ISSUE TITLE
User Friendly Inputs

### ISSUE THREAD

**Issue by Ashit743** [Daksh777/TakeABreak#111]
### Is your feature request related to a problem? Please describe.

Add site link or Enter website directly can be user friendly to take user inputs, for example, if the user input is facebook then we can add 'https//:' prefix and '.com' suffix 

### Describe the solution you'd like.

using regex

### Describe alternatives you've considered.

considered auto-suggestion feature for sites if users enter it wrong.

**Comment by Daksh777** [comment]
@Ashit743 that is exactly why we have quick links below the direct input box, I don't think we will need something like that.

**Comment by Ashit743** [comment]
@Daksh777  check this out
![Screenshot (136)](https://user-images.githubusercontent.com/63945407/159152672-c7230748-baae-43d6-a355-b19c5e103b3a.png)
![Screenshot (137)](https://user-images.githubusercontent.com/63945407/159152707-9065e231-b0e5-4a49-beb9-a93089d3d7c1.png)

**Comment by Daksh777** [comment]
Okay, can you explain how you'll go about doing this?

**Comment by Ashit743** [comment]
@Daksh777  I have checked the main.js file function customUrl() where you have checked for 'https://' , and if not found added one similarly  I will try to check if it has a .com at the end and if not I will add one

**Comment by Daksh777** [comment]
But that won't work with websites that do not use .com and use something else like .org

**Comment by Ashit743** [comment]
Interesting case, I will try to use [Url constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL) to catch errors
or other methods mentioned in this [forum](https://stackoverflow.com/questions/5717093/check-if-a-javascript-string-is-a-url)

**Comment by Daksh777** [comment]
I think that would be a lot of unnecessary work and it's not worth it.

**Comment by Ashit743** [comment]
Ok
