### ISSUE TITLE
Adding inspirational time management quotes section.

### ISSUE THREAD

**Issue by RavishaNewase** [Daksh777/TakeABreak#112]
### Is your feature request related to a problem? Please describe.

The features of this website are related to time management. So It will create more impact if we add inspirational quotes about time management.

### Describe the solution you'd like.

I will add a section which will generate random quote only related to time management before visiting to the new website.

### Describe alternatives you've considered.

-

**Comment by RavishaNewase** [comment]
Please assign me this issue under GSSoC'22.

**Comment by Daksh777** [comment]
Please explain more how you'll go about this @RavishaNewase

**Comment by RavishaNewase** [comment]
> Please explain more how you'll go about this @RavishaNewase
After selecting the time to take the break, a one more section will be displayed only for specific time say 5sec, in which a time management quote will be displayed. I can add this section between time selection section and visit website section.

**Comment by Daksh777** [comment]
This is already being worked on in #109
