### ISSUE TITLE
Add Animation to buttons

### ISSUE THREAD

**Issue by PrashantVIT1** [Daksh777/TakeABreak#115]
### Is your feature request related to a problem? Please describe.

This project is related to a person who is looking for some pleasing content, but the buttons are not that interactive.

### Describe the solution you'd like.

I want to add some good hovering animation effects like Popping Bubbles Hover Effect

### Describe alternatives you've considered.

Popping Bubbles Hover Effect is an interactive effect that interacts with the mouse pointer and gives a popping bubbles look on hover. This effect will make the page more interactive, hence increase user visits.

### Add any other context or screenshots about the feature request here.

![image](https://user-images.githubusercontent.com/75080313/159546618-d4423b22-b31e-4aa6-a0ec-1af96b6ddf3e.png)

**Comment by Daksh777** [comment]
I intend to keep the website minimalistic so I don't think any animations would be required, thank you for your suggestion though.
