### ISSUE TITLE
Enhance the buttons styling

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [Daksh777/TakeABreak#116]
### Is your feature request related to a problem? Please describe.

For example when I point the different button it does not change the state of the button it looks the same as it is in this way user cannot easily gets that he or she presses the button or not .Therefore I wan to add some hove effect and enhance its styling. 

### Describe the solution you'd like.

Improve styling of buttons

### Describe alternatives you've considered.

Adding hover effect.

### Add any other context or screenshots about the feature request here.

![hov](https://user-images.githubusercontent.com/89297894/160255323-f9744755-afc6-4709-ad9f-dcedf6d3ba5d.png)

**Comment by Daksh777** [comment]
A hover effect is already present, though it's a bit subtle.
![image](https://user-images.githubusercontent.com/43648146/160268465-21cf1186-2170-48ce-ab8e-ce8d03ddfb6c.png)
