### ISSUE TITLE
Add Hover effects to minutes buttons

### ISSUE THREAD

**Issue by Yasshu55** [Daksh777/TakeABreak#121]
### Is your feature request related to a problem? Please describe.

When we bring our mouse to 5,10,15 and custom minutes buttons there is no Hovering Effect.

### Describe the solution you'd like.

I would like to add the Hover effect to these buttons whenever we move our mouse to it.

### Describe alternatives you've considered.

I can make the Hover Effect However the Mentors want me to or I would add a Simple Hover Effect.

### Add any other context or screenshots about the feature request here.

![hover](https://user-images.githubusercontent.com/95294297/161356741-7eab76c4-f8f8-4529-a4b8-c40a8cdc8490.JPG)

**Comment by Daksh777** [comment]
The hover effect does exist, however, it's only a bit subtle
![image](https://user-images.githubusercontent.com/43648146/161364195-edb77feb-53b2-4f5b-9cd8-16390d7de330.png)

I don't think a change would be required for this.
