### ISSUE TITLE
user confirmation(wants to leave or not ) when user refresh the home page before timeout. 

### ISSUE THREAD

**Issue by vickyrules** [Daksh777/TakeABreak#123]
### Is your feature request related to a problem? Please describe.

If the user accidentally refreshes the home page it ends the break and closes all windows.

, 

### Describe the solution you'd like.

Feature required:
wants a pop-up confirmation [ like -> Want to leave (Yes /no)  ] screen or alert when user refreshes the home page before the break time ends

### Describe alternatives you've considered.

N/A

**Comment by vickyrules** [comment]
assign me.

**Comment by Daksh777** [comment]
Good suggestion @vickyrules 
Make sure to swal for it.
