### ISSUE TITLE
Creating issue templates for the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [Daksh777/TakeABreak#13]
I want to add a few issue templates so that it will be convenient for new contributors to open issues. I plan to create  **Bug Report** and **Feature Request** templates. You can read more about issue templates [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates#issue-templates)

**_The Bug Report issue template will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Screenshots**
- **Desktop Info (OS, Version, Browser etc):**
- **Additional context**

**_The Feature Request issue template will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Timeline- I can complete this task by 3 March**

**Comment by SRADHA-SURESH12** [comment]
Hey there can I work on this issue?

**Comment by Daksh777** [comment]
@MonarchGitHub Could you create issue forms instead?
Read: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by Daksh777** [comment]
> Hey there can I work on this issue?

If @MonarchGitHub is not able to, I'll assign it to you.

**Comment by SRADHA-SURESH12** [comment]
oh okay thank you

**Comment by MonarchGitHub** [comment]
@Daksh777 yes issue form will be better than a template, I'll create it.

**Comment by Daksh777** [comment]
Hey @MonarchGitHub 
Can you please remove the desktop information field?

**Comment by MonarchGitHub** [comment]
yeah sure, on it.
