### ISSUE TITLE
Add uses of Take a Break on Home page

### ISSUE THREAD

**Issue by Kamleshseervi** [Daksh777/TakeABreak#131]
### Is your feature request related to a problem? Please describe.

The uses of this website are not displayed on home page and people will not understand our purpose of this website not properly 

### Describe the solution you'd like.

I request to add some good uses of take a break website below title so that client easily understand purpose of this site

### Describe alternatives you've considered.

We should add some good benefits of using our website on homepage in form of paragraph

**Comment by Daksh777** [comment]
Already present when the website is loaded for the first time:
![image](https://user-images.githubusercontent.com/43648146/161953307-096717f2-b575-4893-9f27-b5b930bd2afd.png)

And the same popup is being added as an info button in the website in #16

**Comment by Kamleshseervi** [comment]
We should show it for all time not for first time

**Comment by Daksh777** [comment]
That's why we're putting an info button for that @Kamleshseervi
