### ISSUE TITLE
Keep browsing option is not functional 

### ISSUE THREAD

**Issue by khushigupta123** [Daksh777/TakeABreak#135]
### What happened?

When the user closes a tab before break time, he receives a pop up on the website asking whether he wants to "Keep browsing" or "I'm done " but on clicking the keep browsing option, nothing happens whereas it was expected that our tab will again be revived and timer will start from where it left.

### How can we reproduce this bug?

On clicking "Keep browsing" option, the user must be again redirected on the same website which he just closed and the timer must begin either from stating or from where it left. 

I am a GSSOC 2022 contributor, please assign this issue to me.

**Comment by Daksh777** [comment]
What I was thinking is that a user will close the website for 2 reasons:
1. To change the website with the remaining break time
2. Accidentally closing the website

So, it makes more sense to have the user select the website themselves than redirecting to the same website.
