### ISSUE TITLE
Adding a sticky note to track or remind what work you have to do after the break

### ISSUE THREAD

**Issue by Anjali-Kedia** [Daksh777/TakeABreak#136]
### Is your feature request related to a problem? Please describe.

We often get so busy or involved in the social media application that we forget what work we had , due to which we end up using the media for longer than decided. 

### Describe the solution you'd like.

If we keep a note of it on the site itself, once the timer goes off we will be reminded of what work we had.
I want an add note option on the website so that I can keep track of my work.

### Describe alternatives you've considered.

If not a sticky note, we can add a message every time we are setting the alarm, that reminds us of the work we had as a pop up when the timer ends.

**Comment by Divya2163** [comment]
I would like to work on this issue under gssoc'22. Can you assign me this?

**Comment by Daksh777** [comment]
@Anjali-Kedia You can add an option in the settings to enable/disable a todo list. Please make sure to add the state of the option (disabled/enabled) to local storage so that the browser "remembers" the state of the setting and also the list of the todos so that it's not lost on reload as well.

**Comment by Anjali-Kedia** [comment]
Yes sir, thank you for the opportunity. I can do it.

**Comment by Daksh777** [comment]
Please try to follow the general design of the website (like fonts, colors, etc) and make sure it's compatible with phones.

**Comment by Anjali-Kedia** [comment]
Thank you, I will keep in mind!

**Comment by Daksh777** [comment]
Yes, sure @MonarchGitHub
