### ISSUE TITLE
Adding custom background image

### ISSUE THREAD

**Issue by Divya2163** [Daksh777/TakeABreak#137]
### Is your feature request related to a problem? Please describe.

The website is simple but looks boring sometimes with a plain dark theme. It would be nice if we add some options to add a background image of the user's choice. I want to consider this issue under gssoc'22.

### Describe the solution you'd like.

We can add a customization option where they can choose the background images given. This would make the website even cooler. I would like to implement this under gssoc'22.

### Describe alternatives you've considered.

As an alternative, we can add a theme with a fixed image like another theme apart from custom and the color theme.

**Comment by Divya2163** [comment]
I would like to work on this issue under gssoc'22. Can you consider this and assign me this.

**Comment by Daksh777** [comment]
I think it would harm the minimalism of the website, and we already have a colorful theme in the settings menu so I'll have to close this
