### ISSUE TITLE
Add theme settings to local storage

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#138]
Just like the other settings options, the theme settings also need to be added to local storage so that the browser "remembers" the state of the setting.

**Comment by mrkc2303** [comment]
Hey @Daksh777 
I can work on this issue. Kindly assign it to me.
Thanks

**Comment by srivastavaritik** [comment]
please assign me this issue under gssoc label

**Comment by srivastavaritik** [comment]
I have created a pull request #151 for this issue. Kindly check and merge if its appropriate. 
Theme is being saved in localStorage  and its working perfectly fine.

**Comment by srivastavaritik** [comment]
kindly check the pr #160
