### ISSUE TITLE
Fix abbreviations for custom time input

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#139]
Currently, the custom time input option only takes in minutes or hours as input and entering anything else (for example, 30s) will be considered as minutes.
What needs to be done:
- Add abbreviation for seconds (s)
- Consider only numbers (without any abbreviation) as minutes
- Consider anything else invalid

**Comment by mhammadsaani** [comment]
Is this beginners friendly?

**Comment by Girlwithasmile** [comment]
I am a gssoc'22 contributer n can fix this.

**Comment by Daksh777** [comment]
It should be fairly easy @mhammadsaani, if you'd like to work on it, let me know. Else, I'll assign it to @Girlwithasmile

**Comment by mhammadsaani** [comment]
Is this beginners friendly?

**Comment by Divya2163** [comment]
I would like to work on this issue under gssoc

**Comment by And-Rahul** [comment]
assign me this issue, I can work on this.

**Comment by Daksh777** [comment]
@Phani-22 should I assign this to @And-Rahul?

**Comment by And-Rahul** [comment]
Yes!

**Comment by Daksh777** [comment]
You may work on it @And-Rahul
