### ISSUE TITLE
A better UI

### ISSUE THREAD

**Issue by Jyo561** [Daksh777/TakeABreak#14]

**Comment by Daksh777** [comment]
Please explain more @Jyo561

**Comment by SRADHA-SURESH12** [comment]
Hey there canI work on this issue?

**Comment by Daksh777** [comment]
Can you please explain what you will be doing for this issue @SRADHA-SURESH12?

**Comment by SRADHA-SURESH12** [comment]
I haven't completely finalised, My idea is to use  a glossy  color than grey, use a bit more soothing font.
 Also add a countdown timer to show the time left.

This is an initial idea, I have to find more ideas, I will update as I get them?

**Comment by Daksh777** [comment]
I intend to keep the website's design this way to make it look simple.
So the fonts and colours won't be changing.
However, a toggle for a dark/colourful theme can be implemented which is already suggested in #7

**Comment by SRADHA-SURESH12** [comment]
ohh okay

**Comment by Daksh777** [comment]
There are quite a few people who want to work on it, if none of them is able to do it, I'll assign it to you
