### ISSUE TITLE
Add better UI to landing page 

### ISSUE THREAD

**Issue by Kuldeepmishra28** [Daksh777/TakeABreak#141]
### Is your feature request related to a problem? Please describe.

Not any bug or problem.

### Describe the solution you'd like.

Wish design a enhanced User interface for the landing page with light and dark mode functionality. 

### Describe alternatives you've considered.

Can add better UI with light mode also by providing more attractive colors and design.

**Comment by Daksh777** [comment]
Thank you for your suggestion, however, I intend to keep the website minimal as it is right now so I don't believe this needs to be done.
