### ISSUE TITLE
buttons are not aligned properly at some resolution

### ISSUE THREAD

**Issue by myhacktech** [Daksh777/TakeABreak#145]
### Is your feature request related to a problem? Please describe.

related to responsiveness
![Screenshot (330)](https://user-images.githubusercontent.com/86517958/165281221-6aabba1e-7a56-4636-9e4c-459358454bc0.png)
![Screenshot (329)](https://user-images.githubusercontent.com/86517958/165281260-0e77a90a-1529-457d-abce-09a5170c3003.png)

### Describe the solution you'd like.

i can make completely responsive

### Describe alternatives you've considered.

buttons size can be decreased at that point of resolution. at 908*835 and 774*835

**Comment by Daksh777** [comment]
You may work on it

**Comment by tasneemahmed123** [comment]
Can. You assign me this issue?

**Comment by myhacktech** [comment]
> Can. You assign me this issue?

I am working on it.

**Comment by tasneemahmed123** [comment]
> Can. You assign me this issue?



> > Can. You assign me this issue?
> 
> I am working on it.

What happen if It is assigned to me and I work on it too?

**Comment by Daksh777** [comment]
Only one person can be assigned to an issue at a time @tasneemahmed123

**Comment by Daksh777** [comment]
Since @tasneemahmed123 asked first, @tasneemahmed123 would you like to work on this or should I assign this to @aachal28?

**Comment by Abhilasha-Jairath** [comment]
I'm a GSSoC'22 contributor. I can work on this issue. Kindly assign this issue to me.

**Comment by Daksh777** [comment]
Since @aachal28  asked first, @aachal28 would you like to work on this or should I assign this to @Abhilasha-Jairath?

**Comment by Daksh777** [comment]
Since there is no reply, you may work on it @Abhilasha-Jairath

**Comment by Anirban-1490** [comment]
@Daksh777 quick assign me this

**Comment by Daksh777** [comment]
@Anirban-1490 please refer to the screenshots in the first comment, the buttons are unresponsive on some certain screen widths

**Comment by Anirban-1490** [comment]
> @Anirban-1490 please refer to the screenshots in the first comment, the buttons are unresponsive on some certain screen widths

ok working on it
