### ISSUE TITLE
Improve the Pausing Functionality

### ISSUE THREAD

**Issue by Anirban-1490** [Daksh777/TakeABreak#148]
### What happened?

The functionality for Pausing is not good. Even after pausing the time still goes on in the background.

Video - 

https://user-images.githubusercontent.com/82874704/166158589-41229570-dd5a-4327-859e-90d8d93ac162.mp4

### How can we reproduce this bug?

Just start a timer and pause it

**Comment by AKD-01** [comment]
please assign me this issue under gssoc label

**Comment by Daksh777** [comment]
Already being worked on in #144, I forgot to close this.
