### ISSUE TITLE
Task remainder

### ISSUE THREAD

**Issue by 99896264** [Daksh777/TakeABreak#15]
Hii @Daksh777, I have an idea but am not sure how to go ahead with it.
Once the timer ends, we can remind the person of the tasks he will enter in his tasks section or a to-do list that either can be a feature or just a note which pops up at the end.

This may create a strong feeling of getting back to work as that's our main motto in the project. 

 Any improvements and suggestions on how to work are welcomed and I want to work on this issue.

**Comment by Daksh777** [comment]
I think it would be great.
My suggestion is that you could add a toggle/switch under the timer buttons to show/hide the to-do list.
The to-do list should appear at the bottom (which is under the pre-added websites)

Please make sure to follow the same design/color system.

**Comment by 99896264** [comment]
Sure, thank you!

**Comment by gopi-png** [comment]
I had be glad to contribute.

**Comment by Daksh777** [comment]
@99896264 is already assigned to it but if you want, you both may work together and collaborate.
Note that the person who creates the PR gets the points and not the other person.

**Comment by Daksh777** [comment]
Any updates @99896264?
It's been more than 7 days

**Comment by 99896264** [comment]
Sorry, I was not able to sort a significant method. Right now, my mid-semester is going on, so I'm not able to give much time to it.
