### ISSUE TITLE
Update colorful theme

### ISSUE THREAD

**Issue by Akramovic1** [Daksh777/TakeABreak#150]
### Is your feature request related to a problem? Please describe.

Update colourful theme with new animation like that
![take a break](https://user-images.githubusercontent.com/58849502/166715847-0865bb2b-c952-4d04-8139-9b001ba4a03a.png)

### Describe the solution you'd like.

adding new styles for colourful theme option.

### Describe alternatives you've considered.

Adding a new CSS file.

**Comment by Daksh777** [comment]
Please change the background of the color theme to these animated blobs and do not change anything else.

**Comment by sb0603** [comment]
I am Gssoc contributor. I would like to work on this issue. Kindly assign it to me.
