### ISSUE TITLE
Tabs closing out early

### ISSUE THREAD

**Issue by Anirban-1490** [Daksh777/TakeABreak#157]
### What happened?

Seems like if you open any tab other than YT, the tab will pause the timer completely and throw the "Closing out early" Pop up.

Video - 

https://user-images.githubusercontent.com/82874704/167904238-0f33c8e3-c753-4edf-b6a5-824664ece1c6.mp4

### How can we reproduce this bug?

Just open any tab other than YT

**Comment by Anirban-1490** [comment]
@Daksh777 seems like someone has already fixed the problem ,  can you check it again

**Comment by Daksh777** [comment]
Yes, I forgot to close this issue, the problem was fixed

**Comment by Anirban-1490** [comment]
> Yes, I forgot to close this issue, the problem was fixed

lol
