### ISSUE TITLE
Add Animations to buttons on the homepage

### ISSUE THREAD

**Issue by NishantSingh-2705** [Daksh777/TakeABreak#158]
### Is your feature request related to a problem? Please describe.

I want to add animated buttons which makes UI look more attractive and passionate.

### Describe the solution you'd like.

Change buttons

### Describe alternatives you've considered.

only want to add attractive buttons that matches the UI.

**Comment by Daksh777** [comment]
Thank you for the suggestion, however, I intend to keep the design minimal and so I'll have to close your issue.
