### ISSUE TITLE
Improve the Timer Animation a Bit More

### ISSUE THREAD

**Issue by Anirban-1490** [Daksh777/TakeABreak#159]
### Is your feature request related to a problem? Please describe.

improve the circular timer animation , to smooth animation rather than tick based

### Describe the solution you'd like.

will be using css custom properties for this one

### Describe alternatives you've considered.

nothing

### Add any other context or screenshots about the feature request here.

video - 

https://user-images.githubusercontent.com/82874704/168447889-76fbb28e-fe39-4842-9cb2-a496faf790b7.mp4

**Comment by Daksh777** [comment]
Looks awesome!

**Comment by Anirban-1490** [comment]
> Looks awesome!

Thank you :)
