### ISSUE TITLE
About section in the website 

### ISSUE THREAD

**Issue by 99896264** [Daksh777/TakeABreak#16]
Hii @Daksh777, 
I felt we could give a small detail as we enter the website (it could be something like Welcome and a short description) or  "About" section, what is Take a break and how it works, at the top right corner as a small button. Any improvements and suggestions on which direction we can go ahead are welcomed, and I want to work on this issue.

**Comment by Daksh777** [comment]
We already display a pop up with a welcome and about message to a visitor who hasn't ever visited the website before.
However, what you could do is put an "i" button/icon on the top left corner of the website to show the same popup.
You can download an SVG icon from https://fonts.google.com/icons

**Comment by 99896264** [comment]
okay, thank you!

**Comment by codervivek5** [comment]
I want to work on this issue under the Gssoc'22. plz assign me for the contribution.

**Comment by Daksh777** [comment]
@codervivek5, @99896264 is already assigned to it. If they are unable to work on this issue, I'll assign you to it

**Comment by Daksh777** [comment]
Any update on this @99896264?
It's been more than 7 days

**Comment by 99896264** [comment]
I couldn't get to know correctly how the overlay/ shadow could be operated
with the ok button in sweetalert format, the rest is done. Currently, my
mid semesters are going on. So not able to give much time.

**Comment by Daksh777** [comment]
Please read the documentation at https://sweetalert2.github.io/
I hope that will make things clear.

**Comment by 99896264** [comment]
> Please read the documentation at https://sweetalert2.github.io/ I hope that will make things clear.
Okay.Thank you.

**Comment by codervivek5** [comment]
I want to work on this issue plz assigned to me....

**Comment by myhacktech** [comment]
hello,can i contribute to this issue?

**Comment by Daksh777** [comment]
It is already assigned to @99896264, @myhacktech

**Comment by rashi1405** [comment]
can you assign me this task?

**Comment by Daksh777** [comment]
@codervivek5 @myhacktech @rashi1405 Would anyone of you like to work on this?

**Comment by rashi1405** [comment]
yes sure sir !! @Daksh777

**Comment by Daksh777** [comment]
Make sure to use the sweetalert2 function for this like I described above @rashi1405

**Comment by ankita-das-26** [comment]
@Daksh777 I want to contribute but I just have one doubt, you just want to add the about section with an icon in left side of the website right? Is there anything else also ?

**Comment by Daksh777** [comment]
Yes, just the "i" button/icon on the top left corner of the website to show the same popup when the user uses the website for the first time.
You can download an SVG icon from https://fonts.google.com/icons

**Comment by kusumita29** [comment]
Can I work on it? @Daksh777

**Comment by Daksh777** [comment]
Any update @ankita-das-26? Should I assign it to @kusumita29?

**Comment by Daksh777** [comment]
You may work on this @kusumita29
