### ISSUE TITLE
The setting options are not displaying properly.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [Daksh777/TakeABreak#167]
### What happened?

- I have noticed that the Setting options are not responsive, due to which they are going out of the page.

Dekstop view:
![image](https://user-images.githubusercontent.com/90326051/170878449-7fa28508-5eaf-4369-854a-59c4ac48769c.png)

Mobile view:
![image](https://user-images.githubusercontent.com/90326051/170878502-7d18eb51-d64a-4405-a748-9b705c0610ce.png)

### How can we reproduce this bug?

- I will improve the CSS and make it responsive. 
- I am a GSSOC'22 participant, kindly assign this issue to me. Thank you.

**Comment by Rishita489** [comment]
Hey @Daksh777 , I am a GSSOC'22 Contributor . Can you please assign this issue to me . I have solve the issue and send the PR . You can review and merge it.

**Comment by Rishita489** [comment]
Hey @Daksh777 , I have made necessary changes in PR . You can review and merge it .

**Comment by Rishita489** [comment]
Hey @Daksh777 , can you please assign GSSOC label to this PR . Today is the last day .

**Comment by Daksh777** [comment]
Done @Rishita489
