### ISSUE TITLE
[DOCUMENTATION] Contributing.md and code_of_conduct.md files are missing

### ISSUE THREAD

**Issue by Susmita-Dey** [Daksh777/TakeABreak#17]
**I want this issue to be assigned to me. I'm a GSSOC'22 participant. I can work on this issue.
I would add both of these files to this repo.**

**Comment by Daksh777** [comment]
This issue is already being worked on in #13

**Comment by Susmita-Dey** [comment]
> This issue is already being worked on in #13

But they are creating only issue templates. I want to add the two files.

**Comment by Daksh777** [comment]
Oh, I'm really sorry. I misread the issue.

**Comment by Susmita-Dey** [comment]
Thanks for assigning it to me.
