### ISSUE TITLE
Changing the background to improve UI

### ISSUE THREAD

**Issue by Anshikaa-Saini** [Daksh777/TakeABreak#175]
### Is your feature request related to a problem? Please describe.

Currently, the background lacks visual appeal and I believe that a more aesthetically pleasing background would enhance the user experience.
As of now, it looks like this:
![image](https://github.com/Daksh777/TakeABreak/assets/143860130/aa41cd16-931b-4056-ab1d-d2eabad95ccd)

Please assign me this issue under IWoC @Daksh777 

### Describe the solution you'd like.

Adding colors and images to the webpage would enhance it.

### Describe alternatives you've considered.

Using different colors to differentiate three different sections of the page: Navbar, Main content and Footer

**Comment by Daksh777** [comment]
Hey Anshika
Thank you for the suggestion! :)

For now, I do not plan to change the design of the website. I'm using Material Design guidelines for the website so I don't think design changes would be relevant as of now.
