### ISSUE TITLE
Contact Section in the website

### ISSUE THREAD

**Issue by Susmita-Dey** [Daksh777/TakeABreak#18]
Contact info like support mail or social media handles can be added to the website.
I want this issue to be assigned to me. I'm a GSSOC'22 participant. I can work on this issue.

**Comment by Daksh777** [comment]
Hi @Susmita-Dey
Thank you for your suggestion. However, I intend to keep the website a one-pager only and not add anything extra.
There are already links to the GitHub repo and my website in the footer of the website so I don't think we'd need a contact page as of now.
