### ISSUE TITLE
Adding an alert when the user adds an empty site link using the add site button.

### ISSUE THREAD

**Issue by rajaditya28** [Daksh777/TakeABreak#19]
Currently, the site allows adding empty sites using the add site button. Also, inspite of the code having a http adder to site links that dont start with http, it doesn't seem to work as expected.

![Screenshot 2022-03-01 123918](https://user-images.githubusercontent.com/68824237/156121853-31cb9174-2795-4fdb-b778-13a0ca8dec0c.png)

![Screenshot 2022-03-01 124149](https://user-images.githubusercontent.com/68824237/156122229-c4ef6e2d-1e55-463e-8fbc-207b6c47358e.png)

Kindly assign me this issue @Daksh777 . I think I can work out a way to make these improvements.

**Comment by Daksh777** [comment]
Good find, I'll assign the issue to you.

**Comment by rajaditya28** [comment]
Thank you for assigning the issue !

**Comment by Sanghu01** [comment]
I want to work on this project.

**Comment by Daksh777** [comment]
@Sanghu01 The issue is already assigned to @rajaditya28, so I can not assign it to you

**Comment by Daksh777** [comment]
To display errors, please use swal which we're using for other dialogues/popups @rajaditya28

**Comment by rajaditya28** [comment]
Okay !

**Comment by rajaditya28** [comment]
I have made the Pull request #36 .
Kindly review it and merge the PR.
Thank You !!
