### ISSUE TITLE
Only single timer is displayed if multiple sites are opened simultaneously

### ISSUE THREAD

**Issue by Rocker2102** [Daksh777/TakeABreak#2]
Only a single timer is displayed _(referring to the first site only)_ **even if multiple websites are opened simultaneously**.

**Comment by Daksh777** [comment]
> Only a single timer is displayed (referring to the first site only) even if multiple websites are opened simultaneously.

I'm not quite sure of a way to display multiple timers since there is also a timer in the tab title. If you have any idea, please feel free to send a PR.

> Also, the timer does not stop if the website(s) is/are manually closed before the timer expires.

That is a bug and needs to be fixed.

**Comment by MeetaHaldar** [comment]
please , assign this issue to me. i want to work on it.

**Comment by Daksh777** [comment]
Hey @MeetaHaldar 
If you are from GSSoC, you need to start contributing from March 1.
I will assign the issue to you now, however, please only start contributing from March 1.

**Comment by MeetaHaldar** [comment]
yes, sure! thankyou

**Comment by Daksh777** [comment]
Hey @MeetaHaldar 
Any progress on the issue?

**Comment by MeetaHaldar** [comment]
@Daksh777  on the way

**Comment by Daksh777** [comment]
Hey @MeetaHaldar
It's been 1 week, have you worked on it?

**Comment by Rishita489** [comment]
@Daksh777  , I would like to work on the issue . Would you assign it to me ?

**Comment by Rishita489** [comment]
I am GSSOC'22 contributor .

**Comment by Daksh777** [comment]
Sure @Rishita489

**Comment by Daksh777** [comment]
Please explain a little on how you'll go about it @Rishita489

**Comment by Rishita489** [comment]
There will be a limit on the number of websites that can be opened with one instance of the app . We will start a different timer whenever a new site is opened on the same instance and after all timers are completed  , time's up go back to work will be displayed .

**Comment by Daksh777** [comment]
Sounds good, you may start working @Rishita489

**Comment by Daksh777** [comment]
Any updates @Rishita489?

**Comment by Rishita489** [comment]
Hey @Daksh777 , I am still working on it  .

**Comment by Anirban-1490** [comment]
can i get some more rundown on it ?

**Comment by Daksh777** [comment]
What do you mean @Anirban-1490?

**Comment by Anirban-1490** [comment]
> What do you mean @Anirban-1490?

i mean what is this issue about? can i get some details on it

**Comment by Daksh777** [comment]
Oh, sure. So, if you open multiple websites (since you can click on the website card/enter the link and it'll open in a new tab), the timer is only shown for the first website. I don't know what can be done to deal with multiple websites, do you know any possible solution?

**Comment by Anirban-1490** [comment]
> Oh, sure. So, if you open multiple websites (since you can click on the website card/enter the link and it'll open in a new tab), the timer is only shown for the first website. I don't know what can be done to deal with multiple websites, do you know any possible solution?

i mean , this dosen't even make any sense.

First, the timer that is shown , it's actual just a general timer , in this time period you can open any tab , and when timer is over then it's time up. but why do i need multiple timers for multiple website ? 

or maybe you are saying upon time over only the first opened tab get's closed but others will stay open .

or maybe you are saying you want to give timer for each tab opened.

**Comment by Daksh777** [comment]
What I meant is that the timer shown in the website and the site title is for the first instance. For example, if I opened YouTube for 5 minutes, and opened Reddit after 2 minutes (for 5 minutes), the timer will be there for only YouTube (which was of 5 minutes) despite the fact that Reddit will close after 5 minutes.
A solution needs to be figured out to have a timer for each website/tab opened through Take A Break.

**Comment by Anirban-1490** [comment]
> What I meant is that the timer shown in the website and the site title is for the first instance. For example, if I opened YouTube for 5 minutes, and opened Reddit after 2 minutes (for 5 minutes), the timer will be there for only YouTube (which was of 5 minutes) despite the fact that Reddit will close after 5 minutes. A solution needs to be figured out to have a timer for each website/tab opened through Take A Break.

just tested

i set a timer of 5 min.
i opened YT

--after 2 min. ---

i opened Reddit

--- 5 min passed ---
Yt closed
reddit closed


i think this should be the expected behaviour . as if reddit closes after 5 min then the break is going up total of 10min.

**Comment by Daksh777** [comment]
You are absolutely correct, I'll close this issue then.

**Comment by Anirban-1490** [comment]
> You are absolutely correct, I'll close this issue then.

Yep
