### ISSUE TITLE
No input error showing if we write noting in custom time

### ISSUE THREAD

**Issue by Payalsahb20220** [Daksh777/TakeABreak#21]
@Daksh777  sir , currently when i click on custom and put nothing in "time in minutes"  and then click  "lets go" no input error showing like in your code a message "you need to write something" should be shown but it only remove custom page. And if we put space instead of enter some value and then click "lets go" then it remove custom page and  slide down .

**Comment by Daksh777** [comment]
@Payalsahb20220 You have already been assigned to this issue in #4 
Did you meant to put a comment there?
