### ISSUE TITLE
Adding header in the page

### ISSUE THREAD

**Issue by aarushimaurya** [Daksh777/TakeABreak#24]
Hey, I am a GSSoC'22 participant. I feel that we should add a header to the page. We can also improve the footer design.

**Comment by Daksh777** [comment]
Can you please elaborate more?

**Comment by aarushimaurya** [comment]
We can add a navbar on the top and also make the footer better

**Comment by Daksh777** [comment]
I don't think we need a navbar. The website is intended to be a one-pager and I want to keep it that way so I don't think that is required.
By improving the footer, what will you exactly be doing?

**Comment by aarushimaurya** [comment]
Okay, if it's a one-pager then it's not required.
