### ISSUE TITLE
Use time abbreviations instead of inputting time in minutes

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#25]
In the custom time input, the time entered is in minutes
This needs to be changed to time abbreviations, for example, 2m and 0.5h (i.e, m -> minutes and h -> hours)

**Comment by fleurdelis07** [comment]
Could you please assign me this issue for GSSOC'22

**Comment by Rishabh-Gaud** [comment]
I am Rishabh Gaud GSSOC'22 participant. I want to solve this issue

**Comment by Daksh777** [comment]
It is already assigned to @fleurdelis07, @Rishabh-Gaud

**Comment by Daksh777** [comment]
Any updates on this @fleurdelis07?
It's been more than 7 days

**Comment by Rishabh-Gaud** [comment]
> Any updates on this @fleurdelis07? It's been more than 7 days

Can I proceed @Daksh777

**Comment by Ashwani132003** [comment]
Hey @Daksh777 I changed min to minutes. 

![Screenshot (1174)](https://user-images.githubusercontent.com/76273539/158533705-f0c0be9a-8b8a-41bf-a21c-92a011ecfe5d.png)

Can you merge it ?

**Comment by Ashwani132003** [comment]
Oh sorry, I see now you want them to abbreviate, let me change them.

**Comment by Ashwani132003** [comment]
IS this one Okay?
![image](https://user-images.githubusercontent.com/76273539/158535547-8bde8dc0-9a70-41b0-b59d-892686dccc50.png)

**Comment by Daksh777** [comment]
@Rishabh-Gaud Any updates?

**Comment by Rishabh-Gaud** [comment]
Thank you for asking Sir, I have to go college urgently  that's reason I'm late

**Comment by Daksh777** [comment]
No worries @Rishabh-Gaud

**Comment by Rishabh-Gaud** [comment]
I resolved the issue please checkout.
