### ISSUE TITLE
docs: Adding issue templates

### ISSUE THREAD

**Issue by Pradumnasaraf** [Daksh777/TakeABreak#27]
### Chnages 
- Adding Issue templates
- Template path **`.github/ISSUE_TEMPLATE`**

###Template Types
![Screenshot from 2022-03-01 18-02-15](https://user-images.githubusercontent.com/51878265/156169779-aa9bd5b2-94be-40db-9512-4e0ae9fc078a.png)

### Template Preview (while creating an issue - bug.)
![Screenshot from 2022-03-01 18-03-48](https://user-images.githubusercontent.com/51878265/156169861-53b91128-a1aa-4751-805e-affb8a4924a3.png)

- Contribution towards GSsoc`22, Thank you

**Comment by Daksh777** [comment]
This is already done in #22
