### ISSUE TITLE
Timer does not stop if the website is manually closed before the timer expires

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#3]

**Comment by vickyrules** [comment]
I think i can fix this. Please allow  me to do so.

**Comment by Daksh777** [comment]
Hey @vickyrules 
If you are from GSSoC, you need to start contributing from March 1.
I will assign the issue to you now, however, please only start contributing from March 1.

**Comment by Daksh777** [comment]
Any update on this @vickyrules?

**Comment by vickyrules** [comment]
I need two more days because of some urgent college work

**Comment by vickyrules** [comment]
I will redirect with you on Monday, with an update regarding the issue

**Comment by Payalsahb20220** [comment]
@Daksh777  sir , if he is unable to solve this issue  in given time period then can you please assign it to me :)

**Comment by Daksh777** [comment]
Sure @Payalsahb20220

**Comment by vickyrules** [comment]
Please assign it to  @Payalsahb20220

**Comment by pavneetkaurx** [comment]
Would wish to contribute in this issue

**Comment by Payalsahb20220** [comment]
@Daksh777 sir , I start working on this issue under GSSOC'22 , please don't assigned to anyone.

**Comment by Daksh777** [comment]
Any updates @Payalsahb20220?

**Comment by Payalsahb20220** [comment]
Sorry sir , i'm little bit busy bcz i 'm going to my college campus .
But anyway i will give u update in 2 days :).

**Comment by HafsaZahran1** [comment]
Hello @Daksh777 ,
If this bug still exist, can I start searching and working on how to solve it please?

**Comment by Daksh777** [comment]
@Payalsahb20220 If you're not able to fix this, I'll assign this to @pavneetkaurx 
@HafsaZahran1 I can only assign it to you if @Payalsahb20220 and @pavneetkaurx are not able to fix this.

**Comment by Rishita489** [comment]
Hello @Daksh777  ,
Can I start searching and working on this issue  please ?

**Comment by Daksh777** [comment]
@Rishita489 It is already assigned to @Payalsahb20220

**Comment by Daksh777** [comment]
Any updates @Payalsahb20220?

**Comment by Daksh777** [comment]
@pavneetkaurx Would you like to work on this?

**Comment by Daksh777** [comment]
@HafsaZahran1 Would you like to work on this?

**Comment by Rishita489** [comment]
hey @Daksh777  , can you assign this issue to me . I can work on it as it can be a subpart of the other issue you assigned to me .

**Comment by HafsaZahran1** [comment]
> @HafsaZahran1 Would you like to work on this?

Yes, please .

**Comment by Daksh777** [comment]
Sorry @Rishita489, since @HafsaZahran1 had asked to be assigned first, I'll have to assign it to them.

**Comment by HafsaZahran1** [comment]
Hello, 
I'm working on the bug and I found that we might add an event tracker so when the user colse the tab it will clear the countdown timer.

**.addEventListener('beforeunload', function(){clearInterval(setInt)});**

But I'm stack at specifying the element name or class to set to be tracked.
Is there any idea or resources that might help?

**Comment by Daksh777** [comment]
There is already code for it, but I'm not sure why it's not working. Check this:

https://github.com/Daksh777/TakeABreak/blob/main/scripts/main.js#L738-L764

**Comment by vickyrules** [comment]
hwt @Daksh777 , i'm ready to contribute again now  .  I have finished all my personal work.
please assign it to me again if he is unable to resolve.
i have solved it already and ready to make a pr.

**Comment by HafsaZahran1** [comment]
@Daksh777 
I noticed that there is no clearInterval() function in function d(), so I tried to place clearInterval() function to stop the countdown timer but still the bug exist. 
I'm still searching and learning about js so it taking some time.

**Comment by Daksh777** [comment]
No worries @HafsaZahran1, you have 7 days time to work on the issue.
I'll also have a look when I'm free and I'll help you out.

**Comment by vickyrules** [comment]
https://github.com/Daksh777/TakeABreak/blob/68c922a52ddaab0a1edde3731975804c3570e045/scripts/main.js#L738-L764


Hey @Daksh777 will you illustrate what you really want to do when user clicks on  [ confirmButtonText: "Keep Browsing!"] 

And i have successfully Stopped the timer and the timeout alert as well when user closed the window manually .

**Comment by Daksh777** [comment]
No worries @HafsaZahran1 

@vickyrules If the user clicks on "Keep Browsing" button, then we will pause the timer and resume it again when the user selects another website. If "I'm done" is selected, then we just end the break.

**Comment by vickyrules** [comment]
Hey @Daksh777 please assign this to me . I solved this issue and ready to make PR.

**Comment by vickyrules** [comment]
check it out here.
https://vickyrules.github.io/TakeABreak/

**Comment by Daksh777** [comment]
Really well done @vickyrules 
One change needs to be made: When you click on the "Keep browsing" button and select a website, the timer shouldn't start until the website is loaded (like it is by default)

**Comment by vickyrules** [comment]
> Really well done @vickyrules One change needs to be made: When you click on the "Keep browsing" button and select a website, the timer shouldn't start until the website is loaded (like it is by default)

@Daksh777  
done 😊.
