### ISSUE TITLE
Title: Could have a button for stopping the break/pausing the break

### ISSUE THREAD

**Issue by AnishkaKesaria** [Daksh777/TakeABreak#35]
### Is your feature request related to a problem? Please describe.

i) Say that someone doesn't want to continue their break and feels that he/she must go back to work.
ii) Also if someone has decided to have a total of 5 mins break in the one hour task. 

### Describe the solution you'd like.

i) A stop button could be added which redirects the user to the home page again.
ii) A pause button would do the job

### Describe alternatives you've considered.

Stop/Pause on the tab

**Comment by monurao123456** [comment]
@Daksh777 
sir i want to work on this .
please assign it to me

**Comment by Daksh777** [comment]
It is already assigned to @AnishkaKesaria, @monurao123456

**Comment by Daksh777** [comment]
Any updates on this @AnishkaKesaria ?
It's been more than 7 days

**Comment by SachinMittal1766** [comment]
Hey @Daksh777, It is more than 7 days. So if they are not working. Pls assign it to me.

**Comment by Daksh777** [comment]
If they do not reply by tomorrow, I'll assign it to you @SachinMittal1766

**Comment by SachinMittal1766** [comment]
Any Updates @Daksh777 ??

**Comment by Daksh777** [comment]
You may work on it @SachinMittal1766

**Comment by vickyrules** [comment]
@Daksh777 if the issue is still exist please assign it to me.

**Comment by vickyrules** [comment]
@Daksh777  is there any pre -implemented code block for this feature or i have to make it from scratch .

**Comment by Daksh777** [comment]
No @vickyrules, no pre-implemented code for any of these issues.

**Comment by vickyrules** [comment]
@Daksh777 
what is this code doing.
https://github.com/Daksh777/TakeABreak/blob/68c922a52ddaab0a1edde3731975804c3570e045/scripts/main.js#L873-L908

**Comment by vickyrules** [comment]
@Daksh777  where you want to put buttons to stop and pause,

**Comment by Anirban-1490** [comment]
umm @Daksh777 is this issue still active , if yes the assign me this :)

**Comment by Daksh777** [comment]
@vickyrules, would you like me to assign this issue to @Anirban-1490?

**Comment by vickyrules** [comment]
> @vickyrules, would you like me to assign this issue to @Anirban-1490?

Go for it.

**Comment by Anirban-1490** [comment]
Thanks will work on it :)
