### ISSUE TITLE
Add check for custom time input

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#4]
The time entered must be number type unlike right now which accepts anything.
In case, the input is not a number type, an error should be displayed.

**Comment by Payalsahb20220** [comment]
Hello @Daksh777 
can u please assign me this issue :)

**Comment by Daksh777** [comment]
Hey @Payalsahb20220
If you are from GSSoC, you need to start contributing from March 1. 
I will assign the issue to you now, however, please only start contributing from March 1.

**Comment by vickyrules** [comment]
If she failed to fix that then 
Please assign it to me.

**Comment by thisisharsh7** [comment]
if this issue is not taken by anyone?
@Daksh777  please assign this to me.
