### ISSUE TITLE
Title: Blog Page

### ISSUE THREAD

**Issue by Siddhi-Mundada** [Daksh777/TakeABreak#42]
### Is your feature request related to a problem? Please describe.

For making a complete website I think blog page is very much important so that readers can thoroughly get to know our goals etc.

### Describe the solution you'd like.

I would like to add blog page containing blogs on procrastination and breaks with beautiful UI.

### Describe alternatives you've considered.

On main page itself we can add this section containing 2-3 blogs.

**Comment by Daksh777** [comment]
Thank you for your suggestion, however, I intend to keep the website short, simple and straight to the point so I don't think a blog will be required anytime soon.
