### ISSUE TITLE
Want to add a Navbar at the Top

### ISSUE THREAD

**Issue by vedsom** [Daksh777/TakeABreak#44]
Hey @Daksh777  I am a GSSOC 2022 participant.
**I would like to add a navbar to your website**.
It will consist different sections like about, contact us, blogs etc.
Also want to add a 
1) About us section
2) Meditation section which will consist some exercise which user can opt to relax instead visiting other sites
3) A game section which consist small games for entertainment
This will surely enhance the website, so please assign me to do this.

**Comment by Daksh777** [comment]
Hi @vedsom
Thank you for the suggestions. 
I do not wish to add anything extra than what the website is intended for. I want to keep the website simple and straight to the point.
