### ISSUE TITLE
Using Audio Alerts to make it look more Interactive

### ISSUE THREAD

**Issue by roushandas02** [Daksh777/TakeABreak#47]
### Is your feature request related to a problem? Please describe.

I have already added 2 desktop notifications for alerting user at 50% and 90% completion of time. 
But there are 2 challenges in using desktop notification :- 
(i) The user has to allow for receiving notification
(ii) It can only be used in secured sites (eg https://.....)

### Describe the solution you'd like.

A good solution to this can be 2 voice alerts at 50% and 90% completion of time. The audio control will not be visible on homepage . We could add a computer generated voice audio . Audio will be heard by user even if he is in other window. In addition, this would make the project more interactive and those user who did not allow notification, can also be reminded of the time.

### Describe alternatives you've considered.

I couldn't think of any other alternative better than this but I'll let you know if I get any.

### Add any other context or screenshots about the feature request here.

Hello @Daksh777 ,
Hope you would see to the suggestion and provide me with your thoughts on this matter.

Thanking you,
Roushan Das,
A GSSOC Contributor.

**Comment by Daksh777** [comment]
That's a good suggestion @roushandas02 but I don't think many people are fond of having websites making sounds without any notice/option
Could you perhaps put a gear/settings icon from https://fonts.google.com/icons in the top-right corner of the website which shows all the settings for the websites, like notifications, sounds, etc?
Let me know if that's possible.

**Comment by roushandas02** [comment]
You mean to say that on clicking that settings icon, options like notifications and sounds will be displayed and on clicking on these options, we can turn off or on the notification and voice alert being sent to the user ?

**Comment by Daksh777** [comment]
That's correct

**Comment by roushandas02** [comment]
Seems a little Challenging but I'll do it

**Comment by Daksh777** [comment]
I'll give you three weeks' time to solve all the issues you are assigned to, do not worry about the time.
Make sure you learn something new from this.

Also, please make sure to follow the colors, designs and fonts of the current website.

**Comment by roushandas02** [comment]
Okay , That would be fine. Thank you for assigning me this.
