### ISSUE TITLE
Mazegame

### ISSUE THREAD

**Issue by starashdeep** [Daksh777/TakeABreak#48]
### Is your feature request related to a problem? Please describe.

Yes, it is related to the problem. Upcoming generation there is a very big problem in increasing IQ of infants. So, I have prepared this game using HTML, CSS and JavaScript virtually to enhance their IQ. 

### Describe the solution you'd like.

The is a maze where children are forced to to use their IQ  and problem solving skills to create a solution for the maze and pass the level. In this I have designed various levels of difficulty for the children in order to sharpen their brain and help them enhance their cognitive skills, hand eye coordination, find effective solutions and virtue of patience.

### Describe alternatives you've considered.

Since in this time of technology each and every child gets a PC or a tablet at a very early age so we can build more mind developing games in order to make them mentally fit. I am also working on the another project based on it. 

### Add any other context or screenshots about the feature request here.

![Screenshot (310)](https://user-images.githubusercontent.com/92468703/156382546-c896cb26-288a-4d49-bd3d-6975a619700d.png)

**Comment by Daksh777** [comment]
Hi @starashdeep 
Thank you for the suggestion but I intend to keep the website as simple and straight to the point as possible so I will have to close this issue.
