### ISSUE TITLE
Add backdrop for custom time input card

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#5]
Add a backdrop to the custom time input like it is there for the custom website card
![image](https://user-images.githubusercontent.com/43648146/155071623-31ee00f0-b25d-4b94-803d-cc4e7a5886ab.png)

**Comment by ankitadam** [comment]
Can you explain more about this issue?

**Comment by sushovanb02** [comment]
@Daksh777 I want to work on this issue (for GSSoC). I'll start contributing from 1st March.

**Comment by Daksh777** [comment]
> Can you explain more about this issue?

By the backdrop, I mean the shadow/black overlay and it doesn't allow you to click anywhere else until the dialogue is closed.
You may go to https://breaks.eu.org and check the backdrop for the custom time input dialogue/card vs the option to add a custom site.

**Comment by Daksh777** [comment]
@sushovanb02 If @ankitadam is not able to work on it, I will assign it to you.

**Comment by sushovanb02** [comment]
> @sushovanb02 If @ankitadam is not able to work on it, I will assign it to you.

okay, can you open some more issues in this project?

**Comment by Daksh777** [comment]
If I do see any issues/enhancements, I will. You are also free to open issues and work on them once approved @sushovanb02

**Comment by ankitadam** [comment]
> > Can you explain more about this issue?
> 
> By the backdrop, I mean the shadow/black overlay and it doesn't allow you to click anywhere else until the dialogue is closed. You may go to https://breaks.eu.org and check the backdrop for the custom time input dialogue/card vs the option to add a custom site.

Okay, got it. I want to work on it as part of GSSoC'22. Please assign it to me.

**Comment by aishalg** [comment]
I can work on this if someone is unable to do so @Daksh777

**Comment by Daksh777** [comment]
Hey @ankitadam 
I'm really sorry but I'll have to close this issue. 
Since we've migrated to swal2, the backdrop is added to all popups by default so, unfortunately, I'll have to close this issue.
