### ISSUE TITLE
Enhancement : Add custom scroll bar

### ISSUE THREAD

**Issue by TG922** [Daksh777/TakeABreak#50]
### Description

- I want to add custom scroll bar for this website.
- It can give your website a chance to stand out compared to the millions of websites using the browser default scrollbar.
- Please assign me on this issue under GSSOC '22.

**Comment by Daksh777** [comment]
HI @TG922 
Thank you for the suggestion. However, I think there is currently no need for a custom scroll bar as the website is very simple and customising it even more would harm it's simplicity.
