### ISSUE TITLE
Title: Attractive_footer

### ISSUE THREAD

**Issue by ayush-agarwal-190** [Daksh777/TakeABreak#51]
### Is your feature request related to a problem? Please describe.

Making the footer look more attractive(copyright and Contact details) by using css

### Describe the solution you'd like.

Using bright colors and changing the size of images will make it user friendly and attractive

### Describe alternatives you've considered.

I couldn't think of any other alternative better than this but I'll let you know if I get any.

**Comment by ayush-agarwal-190** [comment]
Can I work on this and make it look more attractive

**Comment by Daksh777** [comment]
Hi @ayush-agarwal-190 
I intend to keep the footer simple and keep it the way it is. So, I'll have to close your issue, unfortunately.
