### ISSUE TITLE
Change custom site popup to SweetAlert2

### ISSUE THREAD

**Issue by ayush-agarwal-190** [Daksh777/TakeABreak#52]
### Is your feature request related to a problem? Please describe.

![bug q](https://user-images.githubusercontent.com/95439195/156560215-ddd2799c-39ba-42f2-80de-39bc315aca74.png)
The font size of the given box too small to read making it inconvenient to read and understand .

### Describe the solution you'd like.

Using Css we will make it user friendly and make it convenient to understand .

### Describe alternatives you've considered.

![bugsol](https://user-images.githubusercontent.com/95439195/156560882-c67e35c0-490d-457e-b753-aebc4187a664.png)
![Uploading bugsol.png…]()

**Comment by Daksh777** [comment]
I think the font size looks inconsistent so I don't think that looks good.
Would you instead like to work on this: You need to vertically and horizontally center that popup

**Comment by ayush-agarwal-190** [comment]
Yes I would like to work on this ,please assign me the given task

**Comment by Daksh777** [comment]
Hey @ayush-agarwal-190 
We've migrated to sweet alert 2 and I'm thinking to make this popup a part of sweet alert 2 as well.
I'm really sorry but I'll have to ask you to work on doing that instead. 

Here's some documentation that can help you out: 
- https://sweetalert2.github.io/
- https://kepriprov.go.id/assets/plugins/sweetalert/

Please let me know if you can do it.

**Comment by ayush-agarwal-190** [comment]
Yes 

> Hey @ayush-agarwal-190 We've migrated to sweet alert 2 and I'm thinking to make this popup a part of sweet alert 2 as well. I'm really sorry but I'll have to ask you to work on doing that instead.
> 
> Here's some documentation that can help you out:
> 
> * https://sweetalert2.github.io/
> * https://kepriprov.go.id/assets/plugins/sweetalert/
> 
> Please let me know if you can do it.
Yes I would Really Like to discuss it .And work on it .

**Comment by Daksh777** [comment]
Any updates on this @ayush-agarwal-190?
It's been more than 7 days

**Comment by priyanshi1232** [comment]
Hey! Can I work on this under GSSOC'22 ?

**Comment by Daksh777** [comment]
Sure @priyanshi1232

**Comment by Priyanshi662** [comment]
that was my second id please assign this issue to this id

**Comment by Daksh777** [comment]
Any updates @Priyanshi662?

**Comment by AKD-01** [comment]
i want to work on this issue, please assign me this under gssoc

**Comment by AKD-01** [comment]
I have created a pull request #156  for this issue. I am facing an issue in mapping the enter key with the sweeetalert, please guide me through this.

**Comment by Daksh777** [comment]
Please have a look here, it explains how to throw an error and map keys: https://sweetalert2.github.io/recipe-gallery/login-form.html
