### ISSUE TITLE
Adding voice to suggest the user about time felt

### ISSUE THREAD

**Issue by ayush-agarwal-190** [Daksh777/TakeABreak#53]
### Is your feature request related to a problem? Please describe.

If suppose a user is doing something important and suddenly we terminate the website the user will get a bad experience about the website .
Instead  we can have a reset button and a alert sound like "Your website will terminate soon"  to make the user aware that it website will terminate soon 

### Describe the solution you'd like.

We can add sound like a "Your website will terminate one minute" which will aware the user about the termination .

We can add a reset button ....if user want to spend more time the selected site  

### Describe alternatives you've considered.

.

**Comment by Daksh777** [comment]
This is already being done in #47
