### ISSUE TITLE
Title: replacing 5sec redirecting timer with some qoutes or changing css of that page

### ISSUE THREAD

**Issue by rashita79** [Daksh777/TakeABreak#55]
### Is your feature request related to a problem? Please describe.

Instead of showing 5 sec warning or response time for redirecting we can change the apperance of the page by adding motivational quotes reminding of their purpose of accesing that website.

### Describe the solution you'd like.

Changing user interface of that page and having things that would make the user understand that the aim is to take a short break and then get back to work.

### Describe alternatives you've considered.

changing the css of that redirecting page

**Comment by Daksh777** [comment]
Good idea @rashita79 
While we can keep the 5-second timer, we could also show some motivational quotes on the loading page instead of the purpose of the website.
You may start working on it. A function to fetch motivational quotes was implemented in #23 so you can make use of that.

**Comment by sonalgaud12** [comment]
Hello @Daksh777, I want to work in this issues too.

**Comment by Daksh777** [comment]
Hey @sonalgaud12, this issue is already assigned to @rashita79

**Comment by rashita79** [comment]
> Hey @sonalgaud12, this issue is already assigned to @rashita79
If its possible , we can do it together.

**Comment by Daksh777** [comment]
Sure, if you both would like to collaborate, you are allowed to do so but please note that points will only be awarded to the person who creates the PR.

**Comment by Phani-22** [comment]
@Daksh777 I would like to work on this issue, please assign this to me.

**Comment by MOUSAM-AGARWAL** [comment]
want to work on this issue
assign under ggsoc22 label

**Comment by Daksh777** [comment]
It is already assigned to @Phani-22, @MOUSAM-AGARWAL
