### ISSUE TITLE
Title: Adding a focus mode too and tracking working efficiency

### ISSUE THREAD

**Issue by rashita79** [Daksh777/TakeABreak#57]
### Is your feature request related to a problem? Please describe.

we could keep track of the website the user was working on (efficient work not a break) and then we could report the focus mode like exactly how much time he worked on that 

### Describe the solution you'd like.

giving user the option to set a time or track time for their productive work mode.

### Describe alternatives you've considered.

also the complete tracking like focus mode and then we could have a remainder for break mode also

**Comment by Daksh777** [comment]
Could you please elaborate more?
Do you want to make a mode that is opposite of taking breaks (i.e, setting up a timer for working and when the time is up, the tab closes?)
