### ISSUE TITLE
I am new in development field,Can I contribute in this project? i know basics of html and css 

### ISSUE THREAD

**Issue by Saumya2391** [Daksh777/TakeABreak#58]
### Discussed in https://github.com/Daksh777/TakeABreak/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **gigler** February 28, 2022</sup>
I want to contribute in this project bcz i think this project will help me in my personal use.
I do not know any tech used in it.Can you help me or guide in this so that I learn this tech for build or fixing some bug in this project.
Thanks 
</div>

**Comment by Daksh777** [comment]
Yes, you can contribute to this project is you know JS, HTML and CSS.
