### ISSUE TITLE
Title: Making Footer more Attractive

### ISSUE THREAD

**Issue by MadhuSaini22** [Daksh777/TakeABreak#60]
### Is your feature request related to a problem? Please describe.

No, Making footer does not request related to a problem, It will be just for making website more Attractive.

### Describe the solution you'd like.

I will add some styling to the footer, add some links there.

### Describe alternatives you've considered.

Apply CSS and add some Quick links over there on footer.

**Comment by MadhuSaini22** [comment]
Hey @Daksh777  Could you assign me for this task as I'm a GSSOC'22 participant with GSSOC'22 label?

**Comment by ayush-agarwal-190** [comment]
I also wanted to discuss that part that the footer is not visible properly and required a Css touch .
![footer gssoc](https://user-images.githubusercontent.com/95439195/156696377-a8ba32a8-2d8a-4764-8c5f-6d6fe5ae6f45.png)

**Comment by Daksh777** [comment]
Hi @MadhuSaini22 
Thank you for your suggestion. However, I wish to keep the website minimalistic and not style it too much, so I'll have to unfortunately close the issue.
