### ISSUE TITLE
Title: Create a button for manually ending the break

### ISSUE THREAD

**Issue by Simran2337** [Daksh777/TakeABreak#61]
### Is your feature request related to a problem? Please describe.

It's an enhancement feature.

### Describe the solution you'd like.

There can be a situation where the user has taken a break for 15 mins but then he comes back early and want to end the break manually, so there isn't such feature of ending the break manually.

This can be added.

So, please let me know, if this feature can be added.

**Comment by Daksh777** [comment]
Good idea @Simran2337 
However, this is already being done in #35
