### ISSUE TITLE
Add backdrop to the time's up popup

### ISSUE THREAD

**Issue by Simran2337** [Daksh777/TakeABreak#62]
### What happened?

![image](https://user-images.githubusercontent.com/54612637/156728088-f5998d82-83d7-4398-9948-25bd24be17a3.png)

The card is overlapping with the Time's Up text

### How can we reproduce this bug?

It can fixed with proper margin and creating a separate div tag for the same

Let me know if I can work on it.

**Comment by Daksh777** [comment]
@Simran2337 Could you instead add a backdrop/shadow to the time's up card?
(Here's a similar issue but for the custom time input popup: https://github.com/Daksh777/TakeABreak/issues/5)

**Comment by Simran2337** [comment]
@Daksh777  Yes this can be added as a backdrop as well

**Comment by Daksh777** [comment]
Closing because swal2 already does this.
