### ISSUE TITLE
Migrate to sweet alert 2 instead of sweet alert 1

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#64]
We're currently using sweet alert 1 instead of the latest sweet alert 2. This needs to be updated to sweet alert 2 while making sure all the swal popups/alerts work as intended.

**Comment by Simran2337** [comment]
@Daksh777  this is what I came across while working with backdrop
So, All the Sweetalerts has to be updated right?

**Comment by Simran2337** [comment]
I can take up this task as a GSSOC'22 participant. Can you?

**Comment by Daksh777** [comment]
Yes, that's correct @Simran2337 
You may take up this issue.
