### ISSUE TITLE
Enhancement of Delete button with confirmation

### ISSUE THREAD

**Issue by Simran2337** [Daksh777/TakeABreak#68]
### Is your feature request related to a problem? Please describe.

It's an enhancement

### Describe the solution you'd like.

While working on the issue, it was seen that, while deleting the sites that was added manually, it gets deleted without any confirmation message, which can be result of accidental click.

So, confirmation dialog before finally deleting should be done.
Also enhancement of the delete button
![image](https://user-images.githubusercontent.com/54612637/156797674-a6f1c454-3ba5-4c45-9d09-4a18ef548367.png)
it is not differentiated from the site colour.

If this can be done, you can assign it to me.

### Describe alternatives you've considered.

Either alerts or Sweet alerts any of them can be done.

@Daksh777  Can you put down your views for this enhancement

**Comment by Daksh777** [comment]
Good suggestion @Simran2337 
You may start working on it using swal2

**Comment by Simran2337** [comment]
@Daksh777  surelyy!! Thankyou
