### ISSUE TITLE
Add a dark/colourful theme toggle

### ISSUE THREAD

**Issue by Jaideepgarlyal15** [Daksh777/TakeABreak#7]
Hi, Jaideep Singh Garlyal I'm a **contributor**. My plan is to enhance the website by using **Three.js to use 3D background**. Which will look amazing and would be really interesting for the user and keep them **engaging with the 3D effect.**It will give the form a new 3D look. I would like to contribute to this issue. Please assign me this issue.

**Comment by harshitab07** [comment]
Hey @Daksh777 , as per your suggestion for colorful blobs, I would like to work on it. Can you please assign this issue to me?

**Comment by Daksh777** [comment]
If @Jaideepgarlyal15 is unable to do it, I will assign it to you @harshitab07

**Comment by harshitab07** [comment]
@Daksh777  oh sure

**Comment by Daksh777** [comment]
@Jaideepgarlyal15 Would you like to work on this or should I assign it to @harshitab07?

**Comment by adi2002vicky** [comment]
Hey, I'm GSSOC'22 participant. If this issue is still unresolved kindly assign this to me.

Sir i have already created it ,so please can u assign this task to me

**Comment by Daksh777** [comment]
@adi2002vicky, @harshitab07 and @Jaideepgarlyal15 already are/want to work on the issue. If both of them are unable to do it, I'll assign it to you.

**Comment by kalashvasaniya** [comment]
Hey assign it to me!

**Comment by Daksh777** [comment]
@Jaideepgarlyal15 Can you confirm if you'd like to work on this issue or should I assign someone else?

**Comment by harshitab07** [comment]
@harshitab07  Sir if @Jaideepgarlyal15 fails to respond kindly assign this to me.

**Comment by Daksh777** [comment]
I'll wait for 1 day more, if there is no response, I'll assign it to you.

**Comment by Susmita-Dey** [comment]
Hey, I want to work on this issue. I'm GSSOC'22 participant. If this issue is still unresolved kindly assign this to me.

**Comment by kunalkatara12** [comment]
Hey, if this issue is not assigned to anyone, kindly assign this to me.

**Comment by HarshKumarChoudary** [comment]
I would like to work on it. Please assign it to me.

**Comment by Daksh777** [comment]
@harshitab07 I'll assign this issue to you since @Jaideepgarlyal15 has not replied yet.
Please make sure to coordinate with @roushandas02 to add the dark mode/colourful mode toggle to the settings menu he is working on. You both may coordinate on the Discord server.

**Comment by priyanshusingh305** [comment]
I would like to work on this issue

**Comment by Daksh777** [comment]
It is already assigned to @harshitab07

**Comment by Daksh777** [comment]
@adi2002vicky Would you like to work on this?

**Comment by connectnitesh** [comment]
Hi I would love to work on this issue 
I have previously done this kind of work
I play with CSS.
Please assign it to me !
@Daksh777

**Comment by Daksh777** [comment]
Sure @connectnitesh 
Make sure to add a toggle in the settings
