### ISSUE TITLE
Display favicon of new website added on card

### ISSUE THREAD

**Issue by mk-rana** [Daksh777/TakeABreak#73]
**Is your feature request related to a problem? Please describe.**
It's an enhancement

**Describe the solution you'd like.**
While adding your own website, it is seen that there is no favicon/image displayed on the newly created card in most of the cases.
![image](https://user-images.githubusercontent.com/62178824/156863069-62cb3120-9a62-4ad3-b684-e90d0ceec366.png)

To fix this, a simple code can be written to pull the favicon of the requested site and displaying it on the newly created card. This will increase site's appearance and its user friendliness.

Also, in case a website's favicon is missing or there is some error is fetching the favicon, A pre-set WWW favicon can be displayed.
![image](https://user-images.githubusercontent.com/62178824/156863343-e4de3944-4bfc-4384-b2be-cd87a2b4b4f0.png)

If this can be done, you can assign it to me.

**Describe alternatives you've considered.**
Display WWW fevicon.

**Add any other context or screenshots about the feature request here.**
Hello @Daksh777 ,
Hope you would see to the suggestion and provide me with your thoughts on this matter.

### Suggested Solution

**We can tackle this in a few ways:**

1) Look for the favicon.ico at the root of the domain  www.domain.com/favicon.ico

2) Look for a <link> tag with the rel="shortcut icon" attribute

<link rel="shortcut icon" href="/favicon.ico" />

3) Look for a <link> tag with the rel="icon" attribute

<link rel="icon" href="/favicon.png" />

The latter two will usually yield a higher quality image.

**Comment by Daksh777** [comment]
That is already being done using clearbit API
https://github.com/Daksh777/TakeABreak/blob/main/scripts/main.js#L763-L764

**Comment by mk-rana** [comment]
Then we can enhance it using Google S2 convertor, it can get almost all favicons. Read  here : [Google S2](https://www.labnol.org/internet/get-favicon-image-of-websites-with-google/4404/)

Or we can still improve using another faster api like Get Favicon API.

**Comment by Daksh777** [comment]
That'd be great, would you like to work on doing that @mk-rana?

**Comment by mk-rana** [comment]
Yes I want work on this.

**Comment by mk-rana** [comment]
Hi Daksh
Just a short help needed

I have changed this current code:
![image](https://user-images.githubusercontent.com/62178824/157224006-e4e4d381-c617-4e30-be51-dd43ed2c5e18.png)


To:
![image](https://user-images.githubusercontent.com/62178824/157223712-cf30e3d2-dd7b-426a-9793-79b0e0a7e2b2.png)

And I am getting the following error on local server when a new card is created and the favicon is loaded:
![image](https://user-images.githubusercontent.com/62178824/157224306-16a4cb36-8676-4efe-a4a8-03b973d05772.png)

Actually the domain ->
www.google.com/s2/favicons?domain=https://www.theverge.com/ 
in
http://127.0.0.1:5500/www.google.com/s2/favicons?domain=https://www.theverge.com/ 
error above works fine and fetches the favicon perfectly.

It is the "http://127.0.0.1:5500/" appended infront that's causing error. I can't find the solution to it. Or is it that a production server will automatically handle it?

**Comment by Daksh777** [comment]
Hey @mk-rana 
Can you create a PR? I'll test it locally and let you know of a possible fix.

**Comment by mk-rana** [comment]
PR created. Let me know what changes to be done. Thanks

**Comment by Vrushali-anil-Chaudhari** [comment]
I will like to work on this issue

**Comment by kakkarot0** [comment]
please assign me this issue

**Comment by Daksh777** [comment]
I've assigned it to @Vrushali-anil-Chaudhari because they asked first.
If they're unable to do the work, I'll assign it to you @kakkarot0

**Comment by Daksh777** [comment]
Would you like to work on this @kakkarot0?

**Comment by kakkarot0** [comment]
Yes I'm in

**Comment by Abhilasha-Jairath** [comment]
I'm a GSSoC'22 contributor. I can work on this issue. Kindly assign this issue to me.

**Comment by Daksh777** [comment]
Any update @Abhilasha-Jairath? Sorry for the hurry but since GSSOC is about to end, I'd suggest you to be a little bit quicker.

**Comment by Anirban-1490** [comment]
@Daksh777 assign me this i will try. and explain the issue a bit . do i need to fetch the favicon fron the goolge s2 url and show it in that card for custom websites?

**Comment by Daksh777** [comment]
You need to fetch the favicon of the website URL inputted in the custom website option and show it in the card @Anirban-1490

**Comment by Anirban-1490** [comment]
> You need to fetch the favicon of the website URL inputted in the custom website option and show it in the card @Anirban-1490

ok trying
