### ISSUE TITLE
URL Validation for site link in  'Add Custom Site'

### ISSUE THREAD

**Issue by shreyamedehal** [Daksh777/TakeABreak#76]
### Is your feature request related to a problem? Please describe.

In the 'Add Custom Site' pop-up, URL validation is needed for the site link

![image](https://user-images.githubusercontent.com/82696347/156884501-4c8b4e6f-5d0d-48a7-9844-918aac561f8b.png)

### Describe the solution you'd like.

I would like to add URL validation using regex. Hence if an incorrect URL is entered, a message will be displayed below the link input box. I shall adhere to the styling of the site.

### Describe alternatives you've considered.

--

**Comment by Daksh777** [comment]
Good suggestion @shreyamedehal 
You may go ahead and work on it.
