### ISSUE TITLE
Improve UI of the timer when its ticking

### ISSUE THREAD

**Issue by mahiiverse1** [Daksh777/TakeABreak#78]
### Is your feature request related to a problem? Please describe.

So I'm using the website and I think instead of the screen showing "x minutes remaining!" I could improve the UI a bit and make it look more different like maybe a circular clock like graphics with the time ticking inside it and it changes the grey tone as the timer is closer to self destruct. I'm think of removing the "- minutes remaining" part and show the time left with a simple graphic instead.

### Describe the solution you'd like.

I will use simple CSS and JS to make a simple UI. nothing very complicated. a clock-like circular display for the timer instead of the words. as the timer is close to self destruct a greyer shade 'fills' the circle like water (but not quite water just shade). to enhance ui.

### Describe alternatives you've considered.

as said above.

### Add any other context or screenshots about the feature request here.

Kindly look into this and if you would like me to work on it, please assign me this issue

**Comment by Daksh777** [comment]
Hey @mahiiverse1 
Thank you for the suggestion. I believe that adding a clock will harm the simplicity and minimalism of the website.
However, something like this would be really nice: 
![image](https://user-images.githubusercontent.com/43648146/156917731-c6d44f30-145c-4a6d-ba00-78cbc0ed8cef.png)
Can you do that?

**Comment by Simran2337** [comment]
@Daksh777  I can take up this issue , if not taken
Thanks

**Comment by mahiiverse1** [comment]
hi actually my plan was to do something exactly like that maybe i explained
it a little different way but yeah i was planning to do exactly that

**Comment by mahiiverse1** [comment]
hey thanks for assigning! just to confirm, whats the deadline to submit? is it a week?

**Comment by Daksh777** [comment]
Yes, it's a week @mahiiverse1

**Comment by mahiiverse1** [comment]
@Daksh777 hey so i started working on this about 2 days ago and im having issues with trying to implement it, im also new to this so maybe thats why too, everytime i implement it, it also messes up the main screen that says select a timer so im having troubles implementing this

**Comment by Daksh777** [comment]
Sure @mahiiverse1 but note that the person who creates the PR will get the points and not the other one.
If anyone still wants to collaborate with you, they may do it.

**Comment by mahiiverse1** [comment]
Okay sure thats fine as long as i can learn this from them

**Comment by Daksh777** [comment]
@Simran2337 would you like to join @mahiiverse1?

**Comment by kalashvasaniya** [comment]
Can I try to improve!

**Comment by Anjuli08** [comment]
I would like to work on this issue

**Comment by Daksh777** [comment]
Any updates @kalashvasaniya 
Should I assign it to @Anjuli08 instead?

**Comment by kalashvasaniya** [comment]
> Any updates @kalashvasaniya?
> Should I assign it to @Anjuli08 instead?

Sorry For delay but my exam is going on So ya assign to someone else :)

**Comment by Anirban-1490** [comment]
what kind of UI is needed ?

**Comment by Anirban-1490** [comment]
> what kind of UI is needed ?

@Daksh777

**Comment by Daksh777** [comment]
We need to replace the text timer with something like this @Anirban-1490 :
![image](https://user-images.githubusercontent.com/43648146/167249009-90fdf903-37a0-4772-b55e-027dd70aa851.png)

**Comment by Anirban-1490** [comment]
> We need to replace the text timer with something like this @Anirban-1490 : ![image](https://user-images.githubusercontent.com/43648146/167249009-90fdf903-37a0-4772-b55e-027dd70aa851.png)

Will this UI work? I have created it myself


https://user-images.githubusercontent.com/82874704/167249284-4f1dfc14-19c5-460e-9770-8cb18e859d98.mp4

**Comment by Daksh777** [comment]
That looks good, only the blinking colon needs to be made static and the time's text needs to be brought a little closer. And the red color should be the blue color used in the website.

**Comment by Anirban-1490** [comment]
> That looks good, only the blinking colon needs to be made static and the time's text needs to be brought a little closer. And the red color should be the blue color used in the website.

This good ?


https://user-images.githubusercontent.com/82874704/167250772-462b0d04-f5d7-4032-b073-3bc74243fc8e.mp4

**Comment by Daksh777** [comment]
Could you change the colons to circles instead of squares? And the purple color should be `#8cb3ee` instead. Everything else looks good!

**Comment by Anirban-1490** [comment]
> Could you change the colons to circles instead of squares? And the purple color should be `#8cb3ee` instead. Everything else looks good!

ok thanks i will improve these areas , assign me this issue btw
