### ISSUE TITLE
Alert before closing the site suddenly after completion of time

### ISSUE THREAD

**Issue by roushandas02** [Daksh777/TakeABreak#8]
Hello @Daksh777 ,

My suggestion is as follows:
Suppose any person started the timer and is exploring his entered site with full concentration, no one would pay any heed to the timer running on tab and then it would be too irritating if the site suddenly closes after the completion of entered time. The user experience would be at stake. In this case I would suggest to **drop 2 time alerts at 50% and 90% completion of time.**

Have a look at my suggestion and drop your valuable comments.

Thanking You,
Roushan Das, 
A GSSOC Contributor.

**Comment by Daksh777** [comment]
Those are absolutely amazing suggestions @roushandas02 
Can you please create separate issues for each of the suggestions? I'll assign them to you and discuss a bit about them.

**Comment by roushandas02** [comment]
Sure @Daksh777 , I'll create separate issues for the second and third one right away
and thanks for your appreciation and support.

**Comment by Daksh777** [comment]
Great suggestion @roushandas02 
Can you tell me what will you be using to show the notifications?
I was hoping if we could implement browser push notifications (for both mobile and desktop) using the notification API: https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

**Comment by roushandas02** [comment]
First of all, thank you to assign me this task. Secondly, I think I would require 2 - 3 days to analyze the problem deeply and then form a plan of action regarding the same. I would try to explore your idea and extract beneficial information out of it. I will start my work from 1st March.

**Comment by Daksh777** [comment]
Sounds good, feel free to take your time.
