### ISSUE TITLE
Remember settings state using local storage

### ISSUE THREAD

**Issue by Daksh777** [Daksh777/TakeABreak#81]
Currently, the settings menu's toggles are reset back on reload. This can be fixed by adding their configuration in local storage.
![image](https://user-images.githubusercontent.com/43648146/156918304-9bea9bea-ab42-4881-9763-2e3e3a2f8071.png)

**Comment by Simran2337** [comment]
@Daksh777  I can take up this
Can you please assign it to me?

**Comment by nishant3721** [comment]
@Daksh777 Can I work on it?

**Comment by Daksh777** [comment]
This issue's PR was approved and merged, I forgot to close it @nishant3721, sorry for that
