### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by Areebah03** [Daksh777/TakeABreak#82]
### Is your feature request related to a problem? Please describe.

Improve the UI of website.

### Describe the solution you'd like.

I would like to add background image.

### Describe alternatives you've considered.

Background slider would look good.

**Comment by Khushi25pandey** [comment]
I would like to work on the task. Please assign it to me @Areebah03

**Comment by Daksh777** [comment]
Hi, we're already adding a dark/colorful mode toggle already, I'll have to close this issue unfortunately.
