### ISSUE TITLE
ENHANCED UI

### ISSUE THREAD

**Issue by pavneetkaurx** [Daksh777/TakeABreak#84]
### Is your feature request related to a problem? Please describe.

To enhance the user interface of the website by adding graphic involved background

### Describe the solution you'd like.

Using advance CSS would add a innovative background  to make it look catchy and presentable.

### Describe alternatives you've considered.

A live background with animation would be more presentable rather than a solid static one.

**Comment by Daksh777** [comment]
Duplicate of #82
