### ISSUE TITLE
Timer Intimation

### ISSUE THREAD

**Issue by pavneetkaurx** [Daksh777/TakeABreak#85]
### Is your feature request related to a problem? Please describe.

The timer should show a last countdown that the break is about to end and not just end abruptly .

### Describe the solution you'd like.

Adding a last 10 sec counter so that no shut downs are done abruptly and the user winds up the break things in time.

### Describe alternatives you've considered.

Adding a clock  or a basic counter would help the user to plan things accordingly in due time.

**Comment by Daksh777** [comment]
Hi @pavneetkaurx 
We've already implemented voice alerts for tackling this in #79
