### ISSUE TITLE
Changing CSS and adding motivational pictures

### ISSUE THREAD

**Issue by naugsss** [Daksh777/TakeABreak#86]
### Is your feature request related to a problem? Please describe.

The CSS of the site is not that attractive! 
Another problem is that user might take breaks again and again.. Like taking a break immediately when the his previous break ends up.

### Describe the solution you'd like.

We can actually improve the CSS of the site and different icons.. Moreover we can add some motivational pictures so that user feels motivated and doesn't takes break frequently

### Describe alternatives you've considered.

Another alternative is that we can block the selected sites for few minutes after the break so that user doesn't takes another break... May be we can set certain time limit of 10-20 mins after which the site will work otherwise site won't open.. 
In simple words user can't take break again and again immediately after taking a break!!

**Comment by Daksh777** [comment]
Hi @naugsss 
I intend to keep the design the way it is to maintain its simplicity.

Talking about motivational pictures, what you can do is instead of using the motivational quotes in the "time's up" popup, you can use an API to fetch motivational quotes' images. Would you like to do that?

For the site blocking, we can add an option in the settings menu to do that. Would you like to do that?

**Comment by Bhavesh66** [comment]
Hi @Daksh777 i world like to work on this issue can you please assign it to me.

**Comment by Daksh777** [comment]
If @naugsss is unable to do it, I'll assign it to you @Bhavesh66

**Comment by naugsss** [comment]
@Daksh777 Yes, I'm ready and indeed I'll do it!!

**Comment by Aniket-Gaurav** [comment]
I would like to contribute to this issue, can you please assign to me

**Comment by Daksh777** [comment]
It's already assigned to @naugsss, @Aniket-Gaurav

**Comment by Aniket-Gaurav** [comment]
Hi I have done the changes but couldn't find how to push to forked issue and i have also send the link of my updated fork

**Comment by Aniket-Gaurav** [comment]
Hey I have send you the link of my updated fork and i didn't received any
update from your side and you have closed the issue.

**Comment by Daksh777** [comment]
Please check the Discord messages @Aniket-Gaurav 
I have linked a tutorial for GitHub and Git

**Comment by Aniket-Gaurav** [comment]
Yes at last I managed to pull kindly check and merge. And let me know
about anything new.

**Comment by pushpanjali-10** [comment]
I want to work on this issue, and can work on it on an urgent basis, can you please assign it to me??

**Comment by Aniket-Gaurav** [comment]
Me or you are assigning to other

**Comment by pushpanjali-10** [comment]
I am working on it

**Comment by Daksh777** [comment]
Make sure to use a motivational image API and replace the motivational text with that in the time's up popup.

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.
