### ISSUE TITLE
Improve the UI of the webpage

### ISSUE THREAD

**Issue by shivam123-dev** [Daksh777/TakeABreak#87]
### Is your feature request related to a problem? Please describe.

Upon visiting the webpage there is a scrollbar which is unnecessary. Just want to remove the scrollbar

### Describe the solution you'd like.

Being a GSSOC'22 contributor, I would like to work under this issue.

### Describe alternatives you've considered.

Nil

**Comment by Aniket-Gaurav** [comment]
As the person is going to take a break we can add a section or a website like pinterest, to take advantage of their break to find important information, random and fun facts. 
A section for quotes and more like this.

I am a GSSoC 2022 contributor and i can across this idea about the productive of the user,
So i would like you to assign this to me, Please

**Comment by Daksh777** [comment]
Hi @shivam123-dev 
The scroll bar shouldn't be removed because when users add custom websites, it starts to populate and a scroll bar is necessary.
And a scroll bar is also necessary for accessibility.

**Comment by Daksh777** [comment]
@Aniket-Gaurav Can you please explain your idea more in the GSSoC Discord server?

**Comment by Aniket-Gaurav** [comment]
> @Aniket-Gaurav Can you please explain your idea more in the GSSoC Discord server?

Which server I didn't get a server except GSSoS server

**Comment by Daksh777** [comment]
@Aniket-Gaurav You must have received an invite on your email to join the GSSoC 2022 Discord server

**Comment by Aniket-Gaurav** [comment]
Where is project channel
I couldn't find it
Please Do help.
