### ISSUE TITLE
Option for Extension of time before closing the site

### ISSUE THREAD

**Issue by roushandas02** [Daksh777/TakeABreak#9]
Hello @Daksh777 ,

My Suggestion is, Suppose while exploring, the user gets something that is in the favour of his interest / research / curiosity and he wants to continue with the same. So **before closing the site, there should be a space for extension of time.**

Thanks and Regards,
Roushan Das,
A GSSOC Contributor.

**Comment by Daksh777** [comment]
Great suggestion.
Do you have any idea on the implementation for this? 
I think a good option would be to combine this with the push notification sent when the time is about to end (#8). So, when the push notification is sent that the timer is about to expire, we can add buttons to extend the timer in the push notification.

**Comment by roushandas02** [comment]
Thank you for assigning me this task. I would surely take your suggestion under consideration and try to implement it from 1st March.

**Comment by monurao123456** [comment]
@Daksh777 
sir i also want to work on this issue please assign it to me also

**Comment by Daksh777** [comment]
It cannot be assigned to more than one person @monurao123456

**Comment by roushandas02** [comment]
Hey @Daksh777 ,
If @monurao123456 is interested in this issue, you can unassign me and assign him this issue.

**Comment by Daksh777** [comment]
Sure
@monurao123456 Would you like to work on this? Note that we'll be using the notification API

**Comment by monurao123456** [comment]
Thanks sir , 
  I start working on it.

**Comment by monurao123456** [comment]
@Daksh777 
Sir i am facing error to pushing code to GitHub ,sir please help

**Comment by Daksh777** [comment]
Please ping me on the GSSoC Discord server @monurao123456

**Comment by Saurabh-Suchak** [comment]
hey @monurao123456 , if you want I would like to help you in the implementation of this feature.

**Comment by monurao123456** [comment]
Sure @Saurabh-Suchak

**Comment by tasneemahmed123** [comment]
Hi, I want to work on this feature , can you assign to me please

**Comment by Daksh777** [comment]
It is already to @monurao123456, @tasneemahmed123

**Comment by vickyrules** [comment]
@Daksh777 if still exist assign it to me

**Comment by Daksh777** [comment]
Any updates @vickyrules?

**Comment by vickyrules** [comment]
@Daksh777 My end semester exams are going on so I need some more time.

**Comment by vickyrules** [comment]
If someone asks to be assigned, assign them.

**Comment by vickyrules** [comment]
If they are unable to resolve, I will ask you to reassign later (Probably after exams)

**Comment by Daksh777** [comment]
No problem @vickyrules, good luck with your exams.

**Comment by srivastavaritik** [comment]
i want to work on this issue. please assign me this issue

**Comment by Daksh777** [comment]
Can you tell me how you'd go about implementing it @srivastavaritik?
