### ISSUE TITLE
Adding animation on the settings button.

### ISSUE THREAD

**Issue by J-Harsh** [Daksh777/TakeABreak#90]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/56508036/157057045-69fdc822-67f8-4e53-8a6a-85a955257d1a.png)
This looks a bit cluttered, i would like to change the icons (preferably with blue borders if you allow so)

![image](https://user-images.githubusercontent.com/56508036/157057410-75a9df36-8052-4dc5-b043-cd27d4a090d6.png)
This drop down appears on hover, in-stead of on hover i would like to change it to click and drop with an animation. 

### Describe the solution you'd like.

I would like to add a spin animation on the settings button after removing the on hover drop down, along with cleaner looking icons for the pre-added websites.

### Describe alternatives you've considered.

N/a

**Comment by nishant3721** [comment]
@J-Harsh Can I work on it?

**Comment by J-Harsh** [comment]
It is just a preference but i think smaller icons will look better on pc,i was also thinking to make icons look like this 
![image](https://user-images.githubusercontent.com/56508036/157072382-7d68a137-7d6f-49cf-b153-d6b55f1fc839.png)
, though the icons look clean for mobile view.
For the latter part, yes i can make it happen.

**Comment by Daksh777** [comment]
No, I think it'd be good to keep the icons the way they are currently.
You may work on the animation and hover/active issue.

**Comment by J-Harsh** [comment]
should i change the title and description of this issue to just "change in animations for the settings button" ? It will make it easier for you to track ig

**Comment by Daksh777** [comment]
Yes, please do that
