### ISSUE TITLE
No indication for user to see the time they have selected.

### ISSUE THREAD

**Issue by J-Harsh** [Daksh777/TakeABreak#91]
### Is your feature request related to a problem? Please describe.

So, when someone choses a time their is no indication for the user, regarding which pre-set time they selected, or the custom time they selected.
![image](https://user-images.githubusercontent.com/56508036/157079951-fc38d737-9861-453e-850b-0faf70286e82.png)
It just expand the cards.

### Describe the solution you'd like.

To highlight the selected time as an indication. If a custom time is added, then instead of it saying "Custom" we can replace it with the number of minutes they have entered.

### Describe alternatives you've considered.

N/a

**Comment by aaryahjolia** [comment]
I would like to work on this issue under GSSoC'22. I will add a line after this 4 boxes of time and before 'Enter Website directly' heading which will show something like - 'Selected Time : X minutes' or 'You selected X minutes'. I will also keep the colour scheme and UI in mind.

 I can also do that when user enters a custom time, I will change the inner text of 'Custom' box to the time user entered. Assign me this issue and I will solve both issues as mentioned above by me.

**Comment by J-Harsh** [comment]
> I would like to work on this issue under GSSoC'22. I will add a line after this 4 boxes of time and before 'Enter Website directly' heading which will show something like - 'Selected Time : X minutes' or 'You selected X minutes'. I will also keep the colour scheme and UI in mind.
> 
> I can also do that when user enters a custom time, I will change the inner text of 'Custom' box to the time user entered. Assign me this issue and I will solve both issues as mentioned above by me.

Hey,i like your enthusiasm but i was the one who raised this issue, I don't think i will need any help in solving the issue, though i am open to collaboration if i think I need it. It's my issue and i will like to work on it. @Daksh777 can you assign me this issue

**Comment by satyam1511** [comment]
Hey , I would like to contribute on this issue. Please assign it to me.

**Comment by Daksh777** [comment]
@J-Harsh I'll assign it to you.
Note that collaboration is allowed but points will only be awarded to the one who creates the PR.

Your initial idea is great, you can go ahead with it.

**Comment by J-Harsh** [comment]
@Daksh777 you can close this issue now
