### ISSUE TITLE
svg image cannot be fetched.

### ISSUE THREAD

**Issue by AKD-01** [Daksh777/TakeABreak#92]
### What happened?

../assests/delete.svg cannot be fetched at line 988 in main.js in scripts folder.

### How can we reproduce this bug?

This bug can be reproduced by adding a custom time break. After adding the name and url, there a image-break icon appears at the top of the newly generated icon of the entered website instead of "../assets/delete.svg" .

**Comment by Daksh777** [comment]
I'm unable to reproduce the bug @AKD-01

**Comment by AKD-01** [comment]
![image](https://user-images.githubusercontent.com/83454075/157430169-654da879-83ad-4042-8807-ab61ac5a7249.png)

the delete button on the top of the custom timing icon is appearing as a broken image link.
And please assign this issue as of gssoc

**Comment by Daksh777** [comment]
It works absolutely fine @AKD-01 
![image](https://user-images.githubusercontent.com/43648146/157457173-d5c7cf22-00c9-4b5d-a183-1cf8b285e411.png)

**Comment by AKD-01** [comment]
## Please check this once
https://user-images.githubusercontent.com/83454075/158843898-5d41d3d3-4034-4f39-ac99-d58a2a21d64d.mp4

**Comment by Daksh777** [comment]
Can you please check the network tab? There should be an error there.

**Comment by AKD-01** [comment]
changing "../assets/delete.svg" in img src at line 1003 and 1007 in main.js does the work. Should I create a Pull Request?

**Comment by Daksh777** [comment]
Yes, sure @AKD-01

**Comment by AKD-01** [comment]
created pull request
