### ISSUE TITLE
add some nature image with  motivational thoughts

### ISSUE THREAD

**Issue by Khushbu-kumari-87090** [Daksh777/TakeABreak#95]
### Is your feature request related to a problem? Please describe.

somtime we so much depressed and then  and see the nature and motivational  thoughts we are so much inspire.

### Describe the solution you'd like.

i just want to create front end add some nature image and read the motivational line.

### Describe alternatives you've considered.

i have already mentioned create using front end using page using html,css,java script.

### Add any other context or screenshots about the feature request here.

not this time. but if i complete  then definitely i will add it.

**Comment by Daksh777** [comment]
Hi @Khushbu-kumari-87090 
Someone is already working on implementing motivational images using an API so I'll have to close this issue.
