### ISSUE TITLE
Make year dynamic

### ISSUE THREAD

**Issue by Ashish4321-hub** [Daksh777/TakeABreak#97]
### Is your feature request related to a problem? Please describe.

I want to add some changes to make year dynamic.

### Describe the solution you'd like.

I can add function which match the year to local computer and update year accordingly.

### Describe alternatives you've considered.

We can use api which compare live year to coded year.

### Add any other context or screenshots about the feature request here.

![IMG_20220309_115240](https://user-images.githubusercontent.com/88235823/157384983-9cf2c3dc-4b00-4e9b-b660-cbe686cfe82d.jpg)

**Comment by Daksh777** [comment]
Hi @Ashish4321-hub 
I think you're in the wrong repo. That is my website which is in https://github.com/daksh777/website
