### ISSUE TITLE
Countdown UI 

### ISSUE THREAD

**Issue by SachinMittal1766** [Daksh777/TakeABreak#99]
### Is your feature request related to a problem? Please describe.

The UI of timer is very simple. 

### Describe the solution you'd like.

I think we can modify it to some good UI. I am attaching a video for the same.

https://user-images.githubusercontent.com/82721772/157603349-55f98e58-8769-4504-b30b-cfdc27ce8ea1.mp4

### Describe alternatives you've considered.

One more UI which i think will be good. 
![countdown-timer-digital-counter-circle-smart-phone-ui-design-template-countdown-timer-digital-counter-clock-vector-flat-115007137](https://user-images.githubusercontent.com/82721772/157604428-0da36aac-09cc-4967-8629-0cea292b664d.jpg)

**Comment by Daksh777** [comment]
This is already being done in #78
